In [1]:
...

Ellipsis

In [2]:
Ellipsis

Ellipsis

In [3]:
... is Ellipsis

True

In [4]:
def do_nothing():
    ...

In [5]:
do_nothing()

In [8]:
from flask import Flask

# from custom_stats import count_visitor

app = Flask(__name__)

if app.debug:
    def count_visitor(): ...

@app.route("/")
def home():
    count_visitor()
    return "Hello, world!"

In [9]:
# tuple_example.py

numbers: tuple[int, ...]

# Allowed:
numbers = ()
numbers = (1,)
numbers = (4, 5, 6, 99)

# Not allowed:
numbers = (1, "a")
numbers = [1, 3]

In [11]:
from typing import Callable

def add_one(i: int) -> int:
    return i + 1

def multiply_with(x: int, y: int) -> int:
    return x * y

def as_pixels(i: int) -> str:
    return f"{i}px"

def calculate(i: int, action: Callable[..., int], *args: int) -> int:
    return action(i, *args)

In [12]:
# Works:
calculate(1, add_one)

2

In [13]:
# Works:
calculate(1, multiply_with, 3)

3

In [14]:
# Doesn't work:
calculate(1, 3)

TypeError: 'int' object is not callable

In [15]:
# Doesn't work:
calculate(1, as_pixels)

'1px'

Як ви можете використовувати еліпс для нарізки в NumPy

In [16]:
import numpy as np

dimensions = 3
items_per_dimension = 2
max_items = items_per_dimension**dimensions
axes = np.repeat(items_per_dimension, dimensions)
arr = np.arange(max_items).reshape(axes)
arr

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [17]:
arr[:, :, 0]

array([[0, 2],
       [4, 6]])

In [18]:
import numpy as np

dimensions = np.random.randint(1,10)
items_per_dimension = 2
max_items = items_per_dimension**dimensions
axes = np.repeat(items_per_dimension, dimensions)
arr = np.arange(max_items).reshape(axes)

In [19]:
arr[..., 0]

array([[[[[[[  0,   2],
            [  4,   6]],

           [[  8,  10],
            [ 12,  14]]],


          [[[ 16,  18],
            [ 20,  22]],

           [[ 24,  26],
            [ 28,  30]]]],



         [[[[ 32,  34],
            [ 36,  38]],

           [[ 40,  42],
            [ 44,  46]]],


          [[[ 48,  50],
            [ 52,  54]],

           [[ 56,  58],
            [ 60,  62]]]]],




        [[[[[ 64,  66],
            [ 68,  70]],

           [[ 72,  74],
            [ 76,  78]]],


          [[[ 80,  82],
            [ 84,  86]],

           [[ 88,  90],
            [ 92,  94]]]],



         [[[[ 96,  98],
            [100, 102]],

           [[104, 106],
            [108, 110]]],


          [[[112, 114],
            [116, 118]],

           [[120, 122],
            [124, 126]]]]]],





       [[[[[[128, 130],
            [132, 134]],

           [[136, 138],
            [140, 142]]],


          [[[144, 146],
            [148, 150]],

           [[152, 

Чи три крапки в Python завжди є крапкою?

In [20]:
def hello_world():
    print("Hello, world!")

In [21]:
...

Ellipsis

In [22]:
type(...)

ellipsis